import type { Transaction } from "@/lib/types";

export const transactions: Transaction[] = [
  {
    id: "TRN001",
    employeeId: "EMP001",
    employeeName: "Alice Johnson",
    date: "2024-06-15",
    type: "Advance",
    amount: 500,
    description: "Salary advance for personal emergency.",
    status: "Approved",
  },
  {
    id: "TRN002",
    employeeId: "EMP003",
    employeeName: "Charlie Brown",
    date: "2024-06-10",
    type: "Loan",
    amount: 1000,
    description: "Personal loan, to be deducted in installments.",
    status: "Pending",
  },
    {
    id: "TRN003",
    employeeId: "EMP002",
    employeeName: "Bob Williams",
    date: "2024-06-20",
    type: "Bonus",
    amount: 750,
    description: "Performance bonus for Q2.",
    status: "Paid",
  },
  {
    id: "TRN004",
    employeeId: "EMP005",
    employeeName: "Ethan Davis",
    date: "2024-06-05",
    type: "Deduction",
    amount: 150,
    description: "Company equipment damage.",
    status: "Approved",
  },
   {
    id: "TRN005",
    employeeId: "EMP001",
    employeeName: "Alice Johnson",
    date: "2024-06-22",
    type: "Advance",
    amount: 250,
    description: "Travel expense advance.",
    status: "Rejected",
  },
];